### ISSUE TITLE
Can you please publish the source code for the project

### ISSUE THREAD

**Issue by omon77** [a-patel/LiteXDbHelper#3]
Could you please publish the source code for the project?

**Comment by a-patel** [comment]
For some reason, I cannot publish the source code.

**Comment by malabuyocfritz1984** [comment]
Your project isn't open source?

**Comment by a-patel** [comment]
Yes, it isn't.

**Comment by malabuyocfritz1984** [comment]
Is it paid or? what happened if we use this and you guys decided to abandoned it further down the road?

**Comment by a-patel** [comment]
It is free. NuGet Packages are already published. It won't be removed from there.
